/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as FactCheckingRouteImport } from './routes/fact-checking'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdvertisingRouteImport } from './routes/advertising'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorsIndexRouteImport } from './routes/authors.index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const FactCheckingRoute = FactCheckingRouteImport.update({
  id: '/fact-checking',
  path: '/fact-checking',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingRoute = AdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking': typeof FactCheckingRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/authors/': typeof AuthorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking': typeof FactCheckingRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/authors': typeof AuthorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/contact': typeof ContactRoute
  '/corrections': typeof CorrectionsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-checking': typeof FactCheckingRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/authors/': typeof AuthorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertising'
    | '/contact'
    | '/corrections'
    | '/disclaimer'
    | '/editorial-policy'
    | '/fact-checking'
    | '/mission'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/transparency'
    | '/articles/$slug'
    | '/authors/$slug'
    | '/category/$slug'
    | '/authors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertising'
    | '/contact'
    | '/corrections'
    | '/disclaimer'
    | '/editorial-policy'
    | '/fact-checking'
    | '/mission'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/transparency'
    | '/articles/$slug'
    | '/authors/$slug'
    | '/category/$slug'
    | '/authors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertising'
    | '/contact'
    | '/corrections'
    | '/disclaimer'
    | '/editorial-policy'
    | '/fact-checking'
    | '/mission'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/transparency'
    | '/articles/$slug'
    | '/authors/$slug'
    | '/category/$slug'
    | '/authors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertisingRoute: typeof AdvertisingRoute
  ContactRoute: typeof ContactRoute
  CorrectionsRoute: typeof CorrectionsRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FactCheckingRoute: typeof FactCheckingRoute
  MissionRoute: typeof MissionRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TransparencyRoute: typeof TransparencyRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fact-checking': {
      id: '/fact-checking'
      path: '/fact-checking'
      fullPath: '/fact-checking'
      preLoaderRoute: typeof FactCheckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising': {
      id: '/advertising'
      path: '/advertising'
      fullPath: '/advertising'
      preLoaderRoute: typeof AdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertisingRoute: AdvertisingRoute,
  ContactRoute: ContactRoute,
  CorrectionsRoute: CorrectionsRoute,
  DisclaimerRoute: DisclaimerRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FactCheckingRoute: FactCheckingRoute,
  MissionRoute: MissionRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TransparencyRoute: TransparencyRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
